import { FileOpsEngine } from "../tools/filesystem.js";

export type ProjectGenResult = {
  ok: boolean;
  projectName?: string;
  filesCreated?: string[];
  error?: string;
};

export class ProjectGeneratorEngine {
  constructor(private ops: FileOpsEngine) {}

  async generateProject(name: string): Promise<ProjectGenResult> {
    try {
      this.ops.createFolder(name);
      this.ops.createFolder(`${name}/src`);
      this.ops.createFolder(`${name}/docs`);

      await this.ops.createFile(`${name}/README.md`, `# ${name}\nGenerated by Gidion.`);
      await this.ops.createFile(`${name}/src/index.ts`, "export const demo = () => console.log('Hello');");

      return { ok: true, projectName: name, filesCreated: [`${name}/README.md`, `${name}/src/index.ts`] };
    } catch (err: any) {
      return { ok: false, error: err?.message ?? String(err) };
    }
  }

  async taskCreateBasicProject(name: string): Promise<ProjectGenResult> {
    return this.generateProject(name);
  }
}





